apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: indent-greeting
  namespace: ml-prod
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://greeting-model-s3/models/intent_model_20260530_071135.pkl
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
